// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0jJBKM-Dw1oSqev3IXVgz2w7xF_GR93s',
    appId: '1:731401984311:web:d06f4e1a9b2263f2a662b2',
    messagingSenderId: '731401984311',
    projectId: 'flutter-chat-app-1e96d',
    authDomain: 'flutter-chat-app-1e96d.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1e96d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7NLqaEspGPOZ_0c1O8tfJQBeUDZl2veM',
    appId: '1:731401984311:android:be90e6fbcc17fb6ca662b2',
    messagingSenderId: '731401984311',
    projectId: 'flutter-chat-app-1e96d',
    storageBucket: 'flutter-chat-app-1e96d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnaLdhHQhMJBE-3Brp8I4oYieNH2huEhE',
    appId: '1:731401984311:ios:2c719f561d42f051a662b2',
    messagingSenderId: '731401984311',
    projectId: 'flutter-chat-app-1e96d',
    storageBucket: 'flutter-chat-app-1e96d.appspot.com',
    iosBundleId: 'com.example.flutterAppChat',
  );
}
